<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
exclude-result-prefixes="s">
<xsl:template match="/">
    <html lang="en">
        <head>
            <meta charset="utf-8"/>
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name="viewport"/>

            <!-- START SEO / Meta Tags / Twitter Graph / Open Graph data -->
            <title>XML SiteMap Index</title>

            <!-- START Site Styles -->
            <link rel="stylesheet" href="/assets/css/mainStyles.min.css"/>
            <!-- END Site Styles -->
        </head>
        <body class="skin-blue sidebar-mini" id="guest-bg">
            <div id="main-wrapper">
                <!-- START Main Content -->
                <main id="content">
                    <div id="guest-content-wrapper">
                        <div id="content-wrapper">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div style="margin:0 0 0 0;">
                                            <section class="content-header">
                                                <div class="row guest-page-title">
                                                    <h1 style="text-align: center; margin-top: 1em;">XML Sitemap Index</h1>
                                                </div>
                                            </section>
                                            <div class="content content-guest">
                                                <div class="box box-primary">
                                                    <div class="box-body">
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <p class="expl">Generated by <a href="https://roumen.it/projects/laravel-sitemap/" target="_blank" title="Sitemap generator for Laravel">laravel-sitemap</a>.</p>
                                                                <p class="expl">This sitemap contains <xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> URLs.</p>

                                                                <div class="chart">
                                                                    <table id="sitemap" class="row-border hover order-column sitemap-table" cellspacing="0" width="100%">
                                                                        <thead>
                                                                            <tr>
                                                                                <th style="text-align:left">URL</th>
                                                                                <th style="text-align:left">Updated at</th>
                                                                            </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                            <xsl:for-each select="s:sitemapindex/s:sitemap">
                                                                                <tr>
                                                                                    <td class="url">
                                                                                        <xsl:variable name="itemURL">
                                                                                            <xsl:value-of select="s:loc"/>
                                                                                        </xsl:variable>
                                                                                        <a href="{$itemURL}" target="_blank">
                                                                                            <xsl:value-of select="s:loc"/>
                                                                                        </a>
                                                                                    </td>
                                                                                    <td><xsl:value-of select="concat(substring(s:lastmod,0,11),concat(' ', substring(s:lastmod,12,5)))"/></td>
                                                                                </tr>
                                                                            </xsl:for-each>
                                                                        </tbody>
                                                                        <tfoot>
                                                                            <tr>
                                                                                <th style="text-align:left">URL</th>
                                                                                <th style="text-align:left">Updated at</th>
                                                                            </tr>
                                                                        </tfoot>
                                                                    </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                <!-- END Main Content -->

                <!-- START Main Footer -->
                <footer id="footer-custom-sitemap-index" class="main-footer footer-custom-guest row" style="margin-top:2.5em;">
                    <p class="word-wrap-white-space">Copyright © <a href="https://www.robertattfield.com" title="Rob Attfield Web Developer">Robert Attfield</a> 2016 to 2017. All rights reserved. </p>
                    <p class="word-wrap-white-space">View the original <strong><a href="http://freebtc.website" title="Bitcoin Faucet Rotator">Bitcoin Faucet Rotator</a></strong>. </p>
                </footer>
                <!-- END Main Footer -->
            </div>

            <!-- START Site Scripts/JS -->
            <script src="/assets/js/mainScripts.min.js"/>
            <script src="/assets/js/datatables.net/datatables.min.js"/>
            <script	type="text/javascript"><![CDATA[
				$(document).ready(function() {
				var config = {
					scrollX: true,
					scrollCollapse: true,
					order: [],
					responsive: true,
				};
				$("#sitemap").DataTable(config);
				});]]></script>
        </body>
    </html>
</xsl:template>
</xsl:stylesheet>