<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
        version="1.0"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
        exclude-result-prefixes="s">
    <xsl:template match="/">
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
                <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name="viewport"/>

                <!-- START SEO / Meta Tags / Twitter Graph / Open Graph data -->
                <title>XML SiteMap</title>

                <!-- START Site Styles -->
                <link rel="stylesheet" href="/assets/css/mainStyles.min.css"/>
                <!-- END Site Styles -->
            </head>
            <body class="skin-blue sidebar-mini" id="guest-bg">
                <div id="main-wrapper">
                    <!-- START Main Content -->
                    <main id="content">
                        <div id="guest-content-wrapper">
                            <div id="content-wrapper">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div style="margin:0 0 0 0;">
                                                <section class="content-header">
                                                    <div class="row guest-page-title">
                                                        <h1 style="text-align: center; margin-top: 1em;">XML Sitemap</h1>
                                                    </div>
                                                </section>
                                                <div class="content content-guest">
                                                    <div class="box box-primary">
                                                        <div class="box-body">
                                                            <div class="row">
                                                                <div class="col-lg-12">
                                                                    <p class="expl">Generated by <a href="https://roumen.it/projects/laravel-sitemap/" target="_blank" title="Sitemap generator for Laravel">laravel-sitemap</a>.</p>
                                                                    <p class="expl">This sitemap contains <xsl:value-of select="count(s:urlset/s:url)"/> URLs.</p>
                                                                    <p class="expl">View the <a href="/sitemap" target="_blank" title="Stemap Index">sitemap index</a>.</p>

                                                                    <div class="chart">
                                                                        <table id="sitemap" class="row-border hover order-column sitemap-table" cellspacing="0" width="100%">
                                                                            <thead>
                                                                                <tr>
                                                                                    <th style="text-align:left">URL</th>
                                                                                    <th style="text-align:left">Alternates</th>
                                                                                    <th style="text-align:left">Images</th>
                                                                                    <th style="text-align:left">Videos</th>
                                                                                    <th style="text-align:left">Priority</th>
                                                                                    <th style="text-align:left">Update freq</th>
                                                                                    <th style="text-align:left">Updated at</th>
                                                                                </tr>
                                                                            </thead>
                                                                            <tbody>
                                                                                <xsl:for-each select="s:urlset/s:url">
                                                                                    <tr>
                                                                                        <td class="url">
                                                                                            <xsl:variable name="itemURL">
                                                                                                <xsl:value-of select="s:loc"/>
                                                                                            </xsl:variable>
                                                                                            <a href="{$itemURL}" target="_blank">
                                                                                                <xsl:value-of select="s:loc"/>
                                                                                            </a>
                                                                                        </td>
                                                                                        <td><xsl:value-of select="count(xhtml:link)"/></td>
                                                                                        <td><xsl:value-of select="count(image:image)"/></td>
                                                                                        <td><xsl:value-of select="count(video:video)"/></td>
                                                                                        <td><xsl:value-of select="concat(s:priority*100,'%')"/></td>
                                                                                        <td><xsl:value-of select="s:changefreq"/></td>
                                                                                        <td><xsl:value-of select="concat(substring(s:lastmod,0,11),concat(' ', substring(s:lastmod,12,5)))"/></td>
                                                                                    </tr>
                                                                                </xsl:for-each>
                                                                            </tbody>
                                                                            <tfoot>
                                                                                <tr>
                                                                                    <th style="text-align:left">URL</th>
                                                                                    <th style="text-align:left">Alternates</th>
                                                                                    <th style="text-align:left">Images</th>
                                                                                    <th style="text-align:left">Videos</th>
                                                                                    <th style="text-align:left">Priority</th>
                                                                                    <th style="text-align:left">Update freq</th>
                                                                                    <th style="text-align:left">Updated at</th>
                                                                                </tr>
                                                                            </tfoot>
                                                                        </table>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </main>
                    <!-- END Main Content -->

                    <!-- START Main Footer -->
                    <footer id="footer-custom-sitemap" class="main-footer footer-custom-guest row">
                        <p class="word-wrap-white-space">Copyright © <a href="https://www.robertattfield.com" title="Rob Attfield Web Developer">Robert Attfield</a> 2016 to 2017. All rights reserved. </p>
                        <p class="word-wrap-white-space">View the original <strong><a href="http://freebtc.website" title="Bitcoin Faucet Rotator">Bitcoin Faucet Rotator</a></strong>. </p>
                    </footer>
                    <!-- END Main Footer -->
                </div>

                <!-- START Site Scripts/JS -->
                <script src="/assets/js/mainScripts.min.js"/>
                <script src="/assets/js/datatables.net/datatables.min.js"/>
                <script	type="text/javascript"><![CDATA[
				$(document).ready(function() {
                    var config = {
                        scrollX: true,
                        scrollCollapse: true,
                        order: [],
                        responsive: true,
                    };
                    $("#sitemap").DataTable(config);

                    var contentHeight = $(window).height();
                    var footer = $('#footer-custom-sitemap');
                    if (typeof footer.position() !== 'undefined') {
                        var footerHeight = footer.height();
                        var footerTop = footer.position().top + footerHeight;
                        if (footerTop < contentHeight) {
                            footer.css('margin-top', (contentHeight - (footerTop) - 32) + 'px');
                        }
                    }
				});]]></script>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>